[build]
  base      = "apps/broker-dealer"
  command   = "pnpm build"
  publish   = "apps/broker-dealer/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
